import { Product } from "../../types/product";

export const dummyProducts: Product[] = [
    {
        id:1,
      name: "HP Pavilion 15",
      title: "HP Pavilion 15 - Ryzen 5",
      slug: "hp-pavilion-15",
      price: 72000,
      currency: "Rs.",
      tag: "new",
      category: "Laptop",
      images: ["/products/Frame_68.png"],
      description: "A powerful laptop for daily tasks.",
      specs: {
        Brand: "HP",
        Processor: "Ryzen 5",
        RAM: "8GB",
        Storage: "512GB SSD",
      },
    },
    {
        id:2,
      name: "Dell Inspiron 14",
      title: "Dell Inspiron - Intel i5",
      slug: "dell-inspiron-14",
      price: 68000,
      currency: "Rs.",
      tag: "best seller",
      category: "Laptop",
      images: ["/products/Frame_134.png"],
      description: "Reliable laptop for professionals.",
      specs: {
        Brand: "Dell",
        Processor: "Intel i5",
        RAM: "8GB",
        Storage: "256GB SSD",
      },
    },
    {
        id:3,
      name: "Logitech MX Keys",
      title: "Logitech MX Keys Keyboard",
      slug: "logitech-mx-keys",
      price: 12500,
      currency: "Rs.",
      tag: "limited",
      category: "Keyboard",
      images: ["/products/Frame_136.png"],
      description: "Premium wireless keyboard.",
      specs: {
        Brand: "Logitech",
        Type: "Wireless",
        Backlight: "Yes",
      },
    },
    {
        id:4,
      name: "Lenovo IdeaPad 3",
      title: "Lenovo IdeaPad - Intel i3",
      slug: "lenovo-ideapad-3",
      price: 59000,
      currency: "Rs.",
      tag: "new",
      category: "Laptop",
      images: ["/products/Frame_135.png"],
      description: "Affordable and efficient.",
      specs: {
        Brand: "Lenovo",
        Processor: "Intel i3",
        RAM: "8GB",
        Storage: "512GB SSD",
      },
    },
  ];  