// import { Product } from "../../types/product";

// export const products = [
//   // Gaming Laptops
//   {
//     id: 1,
//     title: "ASUS ROG Strix G15",
//     brand: "ASUS",
//     price: 180000,
//     currency: "NPR",
//     images: ["/products/asus-rog.jpg"],
//     rating: 5,
//     reviews: 25,
//     tag: "Featured",
//     category: "gaming laptop",
//     processor: "AMD Ryzen 7",
//     memory: "16 GB",
//     graphics: "RTX 3060"
//   },
//   {
//     id: 2,
//     title: "Dell G15 Gaming",
//     brand: "Dell",
//     price: 160000,
//     currency: "NPR",
//     images: ["/products/dell-g15.jpg"],
//     rating: 4,
//     reviews: 18,
//     tag: "Gaming",
//     category: "gaming laptop",
//     processor: "Intel Core i7",
//     memory: "16 GB",
//     graphics: "RTX 3050"
//   },
//   {
//     id: 3,
//     title: "HP Pavilion Gaming",
//     brand: "HP",
//     price: 140000,
//     currency: "NPR",
//     images: ["/products/hp-pavilion.jpg"],
//     rating: 4,
//     reviews: 15,
//     tag: "Gaming",
//     category: "gaming laptop",
//     processor: "AMD Ryzen 5",
//     memory: "8 GB",
//     graphics: "GTX 1650"
//   },
//   {
//     id: 4,
//     title: "Acer Nitro 5",
//     brand: "Acer",
//     price: 120000,
//     currency: "NPR",
//     images: ["/products/acer-nitro.jpg"],
//     rating: 4,
//     reviews: 22,
//     tag: "Gaming",
//     category: "gaming laptop",
//     processor: "Intel Core i5",
//     memory: "8 GB",
//     graphics: "GTX 1650"
//   },
//   {
//     id: 5,
//     title: "Lenovo Legion 5",
//     brand: "Lenovo",
//     price: 170000,
//     currency: "NPR",
//     images: ["/products/legion-5.jpg"],
//     rating: 5,
//     reviews: 30,
//     tag: "Gaming",
//     category: "gaming laptop",
//     processor: "AMD Ryzen 7",
//     memory: "16 GB",
//     graphics: "RTX 3060"
//   },
  
//   // Business Laptops
//   {
//     id: 6,
//     title: "Dell Latitude 7420",
//     brand: "Dell",
//     price: 200000,
//     currency: "NPR",
//     images: ["/products/dell-latitude.jpg"],
//     rating: 5,
//     reviews: 12,
//     tag: "Business",
//     category: "business laptop",
//     processor: "Intel Core i7",
//     memory: "16 GB"
//   },
//   {
//     id: 7,
//     title: "Lenovo ThinkPad E14",
//     brand: "Lenovo",
//     price: 150000,
//     currency: "NPR",
//     images: ["/products/thinkpad-e14.jpg"],
//     rating: 4,
//     reviews: 20,
//     tag: "Business",
//     category: "business laptop",
//     processor: "AMD Ryzen 5",
//     memory: "8 GB"
//   },
//   {
//     id: 8,
//     title: "HP EliteBook 840",
//     brand: "HP",
//     price: 180000,
//     currency: "NPR",
//     images: ["/products/hp-elitebook.jpg"],
//     rating: 5,
//     reviews: 8,
//     tag: "Business",
//     category: "business laptop",
//     processor: "Intel Core i7",
//     memory: "16 GB"
//   },
  
//   // Student Laptops
//   {
//     id: 9,
//     title: "ASUS VivoBook 15",
//     brand: "ASUS",
//     price: 80000,
//     currency: "NPR",
//     images: ["/products/asus-vivobook.jpg"],
//     rating: 4,
//     reviews: 35,
//     tag: "Student",
//     category: "student laptop",
//     processor: "Intel Core i5",
//     memory: "8 GB"
//   },
//   {
//     id: 10,
//     title: "Acer Aspire 5",
//     brand: "Acer",
//     price: 70000,
//     currency: "NPR",
//     images: ["/products/acer-aspire.jpg"],
//     rating: 4,
//     reviews: 28,
//     tag: "Student",
//     category: "student laptop",
//     processor: "AMD Ryzen 3",
//     memory: "4 GB"
//   },
//   {
//     id: 11,
//     title: "HP 15s",
//     brand: "HP",
//     price: 65000,
//     currency: "NPR",
//     images: ["/products/hp-15s.jpg"],
//     rating: 3,
//     reviews: 18,
//     tag: "Student",
//     category: "student laptop",
//     processor: "Intel Core i3",
//     memory: "4 GB"
//   },
  
//   // Everyday Laptops
//   {
//     id: 12,
//     title: "Dell Inspiron 15",
//     brand: "Dell",
//     price: 90000,
//     currency: "NPR",
//     images: ["/products/dell-inspiron.jpg"],
//     rating: 4,
//     reviews: 25,
//     tag: "Everyday",
//     category: "everyday laptop",
//     processor: "Intel Core i5",
//     memory: "8 GB"
//   },
//   {
//     id: 13,
//     title: "Lenovo IdeaPad 3",
//     brand: "Lenovo",
//     price: 75000,
//     currency: "NPR",
//     images: ["/products/ideapad-3.jpg"],
//     rating: 4,
//     reviews: 30,
//     tag: "Everyday",
//     category: "everyday laptop",
//     processor: "AMD Ryzen 5",
//     memory: "8 GB"
//   },
  
//   // Mac
//   {
//     id: 14,
//     title: "MacBook Pro 14",
//     brand: "Apple",
//     price: 350000,
//     currency: "NPR",
//     images: ["/products/macbook-pro-14.jpg"],
//     rating: 5,
//     reviews: 15,
//     tag: "Professional",
//     category: "mac",
//     processor: "M2 Pro",
//     memory: "16 GB"
//   },
//   {
//     id: 15,
//     title: "MacBook Air M2",
//     brand: "Apple",
//     price: 180000,
//     currency: "NPR",
//     images: ["/products/macbook-air-m2.jpg"],
//     rating: 5,
//     reviews: 40,
//     tag: "Lightweight",
//     category: "mac",
//     processor: "M2",
//     memory: "8 GB"
//   },
//   {
//     id: 16,
//     title: "MacBook Pro 16",
//     brand: "Apple",
//     price: 450000,
//     currency: "NPR",
//     images: ["/products/macbook-pro-16.jpg"],
//     rating: 5,
//     reviews: 12,
//     tag: "Professional",
//     category: "mac",
//     processor: "M2 Max",
//     memory: "32 GB"
//   },
  
//   // Keyboards
//   {
//     id: 17,
//     title: "Logitech MX Keys",
//     brand: "Logitech",
//     price: 12000,
//     currency: "NPR",
//     images: ["/products/mx-keys.jpg"],
//     rating: 5,
//     reviews: 45,
//     tag: "Wireless",
//     category: "keyboard",
//     connectivity: "Bluetooth",
//     switchType: "Scissor"
//   },
//   {
//     id: 18,
//     title: "Keychron K2",
//     brand: "Keychron",
//     price: 8000,
//     currency: "NPR",
//     images: ["/products/keychron-k2.jpg"],
//     rating: 5,
//     reviews: 35,
//     tag: "Mechanical",
//     category: "keyboard",
//     connectivity: "Wireless",
//     switchType: "Red"
//   },
//   {
//     id: 19,
//     title: "Redragon K552",
//     brand: "Redragon",
//     price: 4500,
//     currency: "NPR",
//     images: ["/products/redragon-k552.jpg"],
//     rating: 4,
//     reviews: 50,
//     tag: "Gaming",
//     category: "keyboard",
//     connectivity: "Wired",
//     switchType: "Blue"
//   },
//   {
//     id: 20,
//     title: "ASUS ROG Strix Scope",
//     brand: "ASUS",
//     price: 15000,
//     currency: "NPR",
//     images: ["/products/asus-rog-keyboard.jpg"],
//     rating: 5,
//     reviews: 20,
//     tag: "Gaming",
//     category: "keyboard",
//     connectivity: "Wired",
//     switchType: "Brown"
//   },
  
//   // Mice
//   {
//     id: 21,
//     title: "Logitech MX Master 3",
//     brand: "Logitech",
//     price: 9900,
//     currency: "NPR",
//     images: ["/products/mx-master-3.jpg"],
//     rating: 5,
//     reviews: 60,
//     tag: "Productivity",
//     category: "mouse",
//     connectivity: "Wireless"
//   },
//   {
//     id: 22,
//     title: "Redragon M652",
//     brand: "Redragon",
//     price: 2500,
//     currency: "NPR",
//     images: ["/products/redragon-m652.jpg"],
//     rating: 4,
//     reviews: 40,
//     tag: "Gaming",
//     category: "mouse",
//     connectivity: "Wired"
//   },
//   {
//     id: 23,
//     title: "ASUS ROG Gladius",
//     brand: "ASUS",
//     price: 6000,
//     currency: "NPR",
//     images: ["/products/asus-rog-mouse.jpg"],
//     rating: 4,
//     reviews: 25,
//     tag: "Gaming",
//     category: "mouse",
//     connectivity: "Wired"
//   },
  
//   // Monitors
//   {
//     id: 24,
//     title: "Dell UltraSharp U2723QE",
//     brand: "Dell",
//     price: 85000,
//     currency: "NPR",
//     images: ["/products/dell-ultrasharp.jpg"],
//     rating: 5,
//     reviews: 15,
//     tag: "4K",
//     category: "monitor",
//     screenSize: "27 inch",
//     resolution: "4K"
//   },
//   {
//     id: 25,
//     title: "ASUS TUF Gaming VG27AQ",
//     brand: "ASUS",
//     price: 45000,
//     currency: "NPR",
//     images: ["/products/asus-tuf-monitor.jpg"],
//     rating: 5,
//     reviews: 30,
//     tag: "Gaming",
//     category: "monitor",
//     screenSize: "27 inch",
//     resolution: "1440p"
//   },
//   {
//     id: 26,
//     title: "HP E24 G5",
//     brand: "HP",
//     price: 25000,
//     currency: "NPR",
//     images: ["/products/hp-e24.jpg"],
//     rating: 4,
//     reviews: 20,
//     tag: "Office",
//     category: "monitor",
//     screenSize: "24 inch",
//     resolution: "1080p"
//   },
//   {
//     id: 27,
//     title: "Acer Nitro XV272U",
//     brand: "Acer",
//     price: 40000,
//     currency: "NPR",
//     images: ["/products/acer-nitro-monitor.jpg"],
//     rating: 4,
//     reviews: 25,
//     tag: "Gaming",
//     category: "monitor",
//     screenSize: "27 inch",
//     resolution: "1440p"
//   },
// ];
// export default products;